var nfa = new NFA( [ 'a', 'b', 'c', 'd' ] );
var nfaview = new NFAView( nfa );

nfa.addState( 'p' );
nfa.addState( 'q' );
nfa.addState( 't' );
nfa.addState( 'r' );
nfa.addState( 'f' );
nfa.addTransition( 's', 'b', 's' );
nfa.addTransition( 's', 'a', 'p' );
nfa.addTransition( 's', 'ε', 'p' );
nfa.addTransition( 's', 'a', 'q' );
nfa.addTransition( 'p', 'b', 'q' );
nfa.addTransition( 'q', 'a', 't' );
nfa.addTransition( 'q', 'b', 't' );
nfa.addTransition( 't', 'a', 's' );
nfa.addTransition( 't', 'b', 's' );
nfa.addTransition( 't', 'a', 'r' );
nfa.addTransition( 't', 'c', 'f' );
nfa.addTransition( 'r', 'ε', 'f' );
nfa.addAcceptingState( 'f' );
nfaview.states[ 's' ].position = new Vector( 100, 200 );
nfaview.states[ 'p' ].position = new Vector( 250, 100 );
nfaview.states[ 'q' ].position = new Vector( 400, 200 );
nfaview.states[ 't' ].position = new Vector( 400, 400 );
nfaview.states[ 'r' ].position = new Vector( 250, 500 );
nfaview.states[ 'f' ].position = new Vector( 100, 400 );
