CREATE TABLE users (
    gid VARCHAR( 32 ) NOT NULL PRIMARY KEY,
    name VARCHAR( 32 ) NOT NULL,
    email VARCHAR( 32 ) DEFAULT NULL,
    picture VARCHAR( 128 ) DEFAULT NULL,
    password VARCHAR( 32 ) DEFAULT NULL,
    created DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE automata (
    id INT unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
    public BOOLEAN NOT NULL DEFAULT 1,
    uid VARCHAR( 32 ) DEFAULT NULL,
    name TEXT NOT NULL,
    data MEDIUMTEXT NOT NULL,
    created DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    FOREIGN KEY (uid) REFERENCES user(id)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
