CREATE TABLE users (
    id INT unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR( 32 ) NOT NULL,
    password VARCHAR( 32 ) DEFAULT NULL,
    email VARCHAR( 32 ) DEFAULT NULL,
    created DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
CREATE TABLE automata (
    id INT unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name TEXT NOT NULL DEFAULT '',
    data MEDIUMTEXT NOT NULL DEFAULT '',
    created DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
